# 모든 레코드 조회하기
SELECT * FROM ANIMAL_INS ORDER BY ANIMAL_ID

# 동물 이름, 보호 시작일을 ID 역순으로 조회
SELECT NAME, DATETIME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC

# 아픈 동물 역순으로 조회
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'SICK'
ORDER BY ANIMAL_ID

# AGED가 아닌 경우 조회
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION  NOT IN('AGED')
ORDER BY ANIMAL_ID

# ID, NAME 조회
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

# 이름 순으로, 이름 동일하면 보호 나중에 시작한 동물 먼저 조회
SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY NAME, DATETIME DESC

# 가장 먼저 들어온 동물 한마리
SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1

