# latest
SELECT DATETIME
FROM ANIMAL_INS
ORDER BY DATETIME DESC
LIMIT 1

# 가장 처음에 들어온 동물 날짜
SELECT DATETIME
FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1

SELECT MIN(DATETIME)
FROM ANIMAL_INS

# 전체 동물 카운트
SELECT COUNT(*)
FROM ANIMAL_INS

# 이름 카운트, 중복 제거, null일 경우 제외
SELECT COUNT(DISTINCT NAME)
FROM ANIMAL_INS
WHERE NAME IS NOT NULL